// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqrvfaapujzrkkpjncml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxcnZmYWFwdWp6cmtrcGpuY21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzk4NjMsImV4cCI6MjA2ODcxNTg2M30.cs61tnFl-h_-3q_UydpjUbQCOyvRU5AWhXbCviCv0hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});